config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  match 'servers/coupling' => 'servers#coupling', as: :coupling, via: [:get, :post]
  get 'servers/connect' => 'servers#connect', as: :connect
  post 'servers/destroy_everything' => 'servers#destroy_everything', as: :destroy_everything
  post 'servers/do_connect' =>'servers#do_connect'
  resources :servers

  get 'welcome/index'

end

app/models/server.rb
class Server < ActiveRecord::Base
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    retrieve_data_for_graph
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  # GET or POST
  def coupling
    retrieve_data_for_graph
    @server1 = params[:neoServer1]
    @server2 = params[:neoServer2]
    if @server1 && @server2
      if @server1 == @server2 #direct coupling

      end
      @server1 = Neography::Node.load(@server1, @neo)
      @server2 = Neography::Node.load(@server2, @neo)
      relationships = {"type" => 'connect', "direction" => "all"}
      # directPath =
      direct_path = @neo.get_node_relationships_to(@server1, @server2)
      if direct_path[0] != nil
        tightness = @neo.get_relationship_properties(direct_path[0], [:tight])[:tight]
        looseness = @neo.get_relationship_properties(direct_path[0], [:loose])[:loose]
        @classical = [tightness, looseness]
        @worst = [tightness, looseness]
        @best = [tightness, looseness]
        @moderate = [tightness, looseness]
      else
        all_paths = @neo.execute_query("
        match (n1) -[r*]- (n2) where id(n1) = " +params[:neoServer1]+ "
        and id(n2) = "+params[:neoServer2]+ " return r")["data"]

        query1 = @neo.execute_query("Start n=node("+params[:neoServer1]+"), p=node("+params[:neoServer2]+") Match l = n - [k*] - p with extract(x in relationships(l)| x.loose) as levels Return  levels")["data"]
        query2 = @neo.execute_query("Start n=node("+params[:neoServer1]+"), p=node("+params[:neoServer2]+") Match l = n - [k*] - p with extract(x in relationships(l)| x.tight) as levels Return  levels")["data"]
        #empty values should never return 0, therefore remove them now.
        query1.map!{ |x| x.map! {|xx| xx.each_index do |i|
          if xx[i] == ""
            xx.delete_at(i)
          end
        end } }
        query2.map!{ |x| x.map! {|xx| xx.each_index do |i|
          if xx[i] == ""
            xx.delete_at(i)
          end
        end } }
        best_case(query1, query2)
        worst_case(query1, query2)
      end
    end
    render 'servers/coupling'
  end

  #GET
  def connect
    retrieve_data_for_graph
  end

  #POST
  def do_connect
    tight = params[:tight_coupling]
    loose = params[:loose_coupling]
    if params[:neoServer1] != params[:neoServer2] && tight && loose
      @neo = Neography::Rest.new
      server1 = Neography::Node.load(params[:neoServer1], @neo)
      server2 = Neography::Node.load(params[:neoServer2], @neo)
      direct_path = @neo.get_node_relationships_to(server1, server2)
      if direct_path[0] != nil #there exists already a relation, so delete that before creating a new one
        @neo.delete_relationship direct_path[0]
      end
      relation = @neo.create_relationship(:connected, server1, server2)
      @neo.set_relationship_properties(relation, {tight: tight})
      @neo.set_relationship_properties(relation, {loose: loose})
      redirect_to action: 'connect', notice: 'Connection was successfully created.'
    else
      redirect_to action: 'connect', alert: 'Connecting a node with itself  or leaving parameters empty is not permitted.'
    end
  end

# POST /servers
# POST /servers.json
  def create
    @server = Server.new(server_params)
    @neo = Neography::Rest.new

    respond_to do |format|
      if @server.save && n = Neography::Node.create("name" => server_params[:name])
        n.add_to_index('servers', 'name', server_params[:name])
        n.id = n.neo_id # this construct should be improved..
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

# PATCH/PUT /servers/1
# PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      name = Server.find(params[:id]).name
      n = Neography::Node.find('servers', 'name', name)
      n.name = server_params[:name]
      n.add_to_index('servers', 'name', server_params[:name]) #TODO: is this necessary?
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /servers/1
# DELETE /servers/1.json
  def destroy
    destroy_server @server
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_everything
    Server.all.each do |server|
      destroy_server server
    end
    redirect_to action: 'index', notice: 'Everything was successfully destroyed.'
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_server
    @server = Server.find(params[:id])
  end

  def destroy_server(server)
    n = Neography::Node.find('servers', 'name', server.name)
    n.del if n
    server.destroy
  end

  def get_all_neo_servers
    @neo = Neography::Rest.new
    @neo.execute_query("match (n) return n limit 50;")["data"]
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def server_params
    params.require(:server).permit(:name)
  end


  def retrieve_data_for_graph
    @servers = Server.all
    @neo_servers = get_all_neo_servers.map { |s| {"server" => s[0]} }
    @nodes = []
    x=y=10 #coordinates
    @neo_servers.each do |neo|
      @nodes << {x: x, y: y, name: neo['server']['data']['name']}
      x += 10; y += 2
    end
    @links = []
    source_id = 0
    @neo_servers.each do |neo|
      server = Neography::Node.load(neo['server']['data']['id'], @neo)
      if server.rel?(:outgoing, :connected)
        relationships = server.rels(:connected).outgoing
        relationships.each do |relationship|

          tightness = @neo.get_relationship_properties(relationship, [:tight])[:tight]
          looseness = @neo.get_relationship_properties(relationship, [:loose])[:loose]
          target_node_id = relationship.end_node[:id]
          target_id = 0 # we need to have relative numbers for d3.js
          @neo_servers.each do |possible_target|
            break if possible_target['server']['data']['id'] == target_node_id
            target_id += 1
          end
          #enter everything into the @links array
          @links << {source: source_id, target: target_id, tight: tightness, loose: looseness}

        end
      end
      source_id +=1 # check out the next source in the next iteration
    end
  end

  def worst_case(loose, tight)
    tightlycouplinglist = []
    @worst = []

    tight.each do |x|
      tightlycouplinglist.append(x[0].min)
    end
    #or

    x = tightlycouplinglist.length
    y = 0

    if x > 1
      while y < x-1
        product = tightlycouplinglist[y].to_f*tightlycouplinglist[y+1].to_f
        sum = tightlycouplinglist[y].to_f+tightlycouplinglist[y+1].to_f
        tightlycouplinglist[y] = sum - product
        y += 1
      end
      @worst[0]=tightlycouplinglist[y-1]
    else
      @worst[0]=tightlycouplinglist[0]
    end
    looselycouplinglist = []
    product = 1.0

    #and
    loose.each do |record| #for some reason, there are strings around.
      record.map! { |xy| xy.map! { |xyz| xyz.to_f } }
    end
    loose.each do |record|
      looselycouplinglist.append(record[0].max)
    end
    #or
    if looselycouplinglist.length > 1
      looselycouplinglist.each { |x| product = product * x.to_f }
      @worst[1]=product
    else
      @worst[1]=looselycouplinglist[0]
    end

  end

  def best_case(loose, tight)
    tightlycouplinglist = []
    tightproduct = 1.0
    @best = []
    #and
    tight.each do |x|
      x[0].each do |y|
        tightproduct = tightproduct * y.to_f
      end
      tightlycouplinglist.append(tightproduct)
      tightproduct = 1.0
    end

    #or
    @best[0]=tightlycouplinglist.max

    #loosely
    looselycouplinglist = []
    product = 1.0
    sum = 0.0
    #and
    loose.each do |record|
      copy = record[0]
      x = copy.length
      y = 0
      if x > 1
        while y < x-1
          product = copy[y].to_f * copy[y+1].to_f
          sum = copy[y].to_f + copy[y+1].to_f
          copy[y] = sum - product
          y += 1
        end
        looselycouplinglist.append(copy[y-1])

      else
        looselycouplinglist.append(copy[0].to_f)
      end
    end
    #or
    @best[1]=looselycouplinglist.min


  end

end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save', class: 'button' %>
  </div>
<% end %>

app/views/servers/connect.html.erb
<h1>Connect two Nodes through fuzzy coupling</h1>

<%= form_tag 'do_connect' do %>

    <div class="row">
      <div class="small-3 columns">
        <div class="row">
          <div class="small-3 columns">
            <label for="right-label" class="right inline">Node 1</label>
          </div>
          <div class="small-9 columns">
            <select name="neoServer1">
              <% @neo_servers.each do |neo| %>
                  <option value="<%= neo['server']['data']['id'] %>"><%= neo['server']['data']['name'] %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="small-2 columns">
        <div class="row collapse prefix-radius">
          <div class="small-6 columns">
            <span class="prefix">Tightly Coupling:</span>
          </div>
          <div class="small-6 columns">
            <%= number_field_tag 'tight_coupling', nil, :step => 0.05, :in => 0..1 %>
          </div>
        </div>
      </div>
      <div class="small-2 columns">
        <div class="row collapse prefix-radius">
          <div class="small-6 columns">
            <span class="prefix">Loosely Coupling:</span>
          </div>
          <div class="small-6 columns">
            <%= number_field_tag 'loose_coupling', nil, :step => 0.05, :in => 0..1 %>
          </div>
        </div>
      </div>
      <div class="small-3 columns">
        <div class="row">
          <div class="small-3 columns">
            <label for="right-label" class="right inline">Node 2</label>
          </div>
          <div class="small-9 columns">
            <select name="neoServer2">
              <% @neo_servers.each do |neo| %>
                  <option value="<%= neo['server']['data']['id'] %>"><%= neo['server']['data']['name'] %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="small-2 columns">
        <%= submit_tag 'Submit', class: 'button postfix' %>
      </div>
    </div>
<% end %>

<div class="panel"><p>The <span class="bold">tightly coupling</span> measurement can be seen as an indicator of risk resulting from the tight connection between two components.
  If one of two tightly coupled components fails, the dependent one will not function properly either.</p>
  <p><span class="bold">Loosely coupling</span> includes the components' resilience  and mitigation into the evaluation.</p>
</div>
<br>
<%= content_tag "div", class: "graph", data: {nodes: @nodes, links: @links} do %>

<% end %>

app/views/servers/coupling.html.erb
<h1>Direct / Indirect Coupling</h1>
<%= form_tag 'coupling' do %>

    <div class="row">
      <div class="small-5 columns">
        <div class="row">
          <div class="small-3 columns">
            <label for="right-label" class="right inline">Node 1</label>
          </div>
          <div class="small-9 columns">
            <select name="neoServer1">
              <% @neo_servers.each do |neo| %>
                  <option value="<%= neo['server']['data']['id'] %>"><%= neo['server']['data']['name'] %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="small-5 columns">
        <div class="row">
          <div class="small-3 columns">
            <label for="right-label" class="right inline">Node 2</label>
          </div>
          <div class="small-9 columns">
            <select name="neoServer2">
              <% @neo_servers.each do |neo| %>
                  <option value="<%= neo['server']['data']['id'] %>"><%= neo['server']['data']['name'] %></option>
              <% end %>
            </select>
          </div>
        </div>
      </div>
      <div class="small-2 columns">
        <%= submit_tag 'Submit', class: 'button postfix' %>
      </div>
    </div>
<% end %>

<% if @server1 != nil && @server2 != nil%>
    Showing dependencies for <span class="bold">
  <%= @server1.name %></span> and <span class="bold"><%= @server2.name %></span>
<table>
  <thead>
  <tr>
    <th>Impact Analysis</th>
    <th>Tightly Coupling</th>
    <th>Loosely Coupling</th>
  </tr>
  </thead>

  <tbody>
  <% if @classical != nil %>
      <tr>
        <td>Classial: It is applicable to the ordinary kind of fuzzy dependencies.</td>
        <td><%= @classical[0] %></td>
        <td><%= @classical[1] %></td>
      </tr>
  <% end %>
  <% if @worst != nil %>
      <tr>
        <td>Worst: The worst case impact analysis uses probabilistic
          disjunciton and classical conjunction to compute the
          indirect impacts. Thus giving a pessimistic view by
          increasing the outcoming value for the degree of membership.</td>
        <td><%= @worst[0] %></td>
        <td><%= @worst[1] %></td>
      </tr>
  <% end %>
  <% if @best != nil %>
      <tr>
        <td>Best: The best case impact analysis uses classical
          disjunction and probabilistic conjunction to compute
          the indirect impacts between the components. It gives
          an optimistic view, meaning that the outcoming value
          for the degree of membership is smaller.</td>
        <td><%= @best[0] %></td>
        <td><%= @best[1] %></td>
      </tr>
  <% end %>
  <% if @moderate != nil %>
      <tr>
        <td>Moderate: The moderate impact analysis uses either a
          probabilistic or a classical approach. It is best
          applicable to the probabilistic dependencies.</td>
        <td><%= @moderate[0] %></td>
        <td><%= @moderate[1] %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>


<%= content_tag "div", class: "graph", data: {nodes: @nodes, links: @links} do %>

<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing Nodes</h1>

<table>
  <thead>
  <tr>
    <th>Node</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @servers.each do |server| %>
      <tr>
        <td><%= server.name %></td>
        <td>
          <ul class="button-group radius">
            <li><%= link_to 'Edit', edit_server_path(server), class: 'button tiny' %></li>
            <li><%= link_to 'X', server, method: :delete, data: {confirm: 'Are you sure?'}, class: 'button tiny alert' %></li>
          </ul>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="button-bar">
  <ul class="button-group radius">
    <li><%= link_to 'New Node', new_server_path, class: 'button default' %></li>
    <li><%= link_to 'Add Relationships ', connect_path, class: 'button default' %></li>
    </li>
  </ul>
  <ul class="button-group radius">
    <li><%= link_to 'Destroy all data', destroy_everything_path, :method => :post, data: {confirm: 'Are you sure?'}, class: 'button alert' %>
    </li>
  </ul>
</div>

<%= content_tag "div", class: "graph", data: {nodes: @nodes, links: @links} do %>

<% end %>

app/views/servers/new.html.erb
<h1>New Node</h1>

<%= render 'form' %>

app/views/servers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @server.name %>
</p>

<%= link_to 'Create another Node', new_server_path, class: 'button' %>
<%= link_to 'Edit', edit_server_path(@server), class: 'button' %>
<%= link_to 'Back to the Nodes', servers_path , class: 'button'%>