config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  match 'servers/coupling' => 'servers#coupling', as: :coupling, via: [:get, :post]
  get 'servers/connect' => 'servers#connect', as: :connect
  post 'servers/destroy_everything' => 'servers#destroy_everything', as: :destroy_everything
  post 'servers/do_connect' =>'servers#do_connect'
  resources :servers

  get 'welcome/index'

end

app/views/layouts/_left_navbar.html.erb
<li><%= link_to 'Nodes', servers_path %></li>
<li><%= link_to 'Connections', connect_path %></li>
<li><%= link_to 'Coupling', coupling_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title><%= content_for?(:title) ? yield(:title) : "Fuzzy Service Level Management" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/modernizer" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="row">
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name"><h1><%= link_to 'Fuzzy SLM', root_path %></h1></li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"></a></li>
    </ul>
    <section class="top-bar-section">
      <!-- Left Nav Section -->
      <ul class="left">
        <%= render '/layouts/left_navbar' %>
      </ul>
      <!-- Right Nav Section -->
      <ul class="right">
        <%= render '/layouts/right_navbar' %>
      </ul>
    </section>
  </nav>
</div>
<div class="row">
  <%= yield %>
  <%= javascript_include_tag "application" %>
</div>
</body>
</html>